<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $novel = Category::where('name', '小説')->first()->id ?? null;
        $business = Category::where('name', 'ビジネス')->first()->id ?? null;
        $tech = Category::where('name', '技術書')->first()->id ?? null;
        $selfhelp = Category::where('name', '自己啓発')->first()->id ?? null;
        $history = Category::where('name', '歴史')->first()->id ?? null;
        $manga = Category::where('name', '漫画')->first()->id ?? null;
        $essay = Category::where('name', 'エッセイ')->first()->id ?? null;

        $books = [
            [
                'title'          => '吾輩は猫である',
                'author'         => '夏目漱石',
                'publisher'      => '新潮社',
                'published_year' => 1905,
                'isbn'           => '978-4-10-109001-7',
                'genre'          => '古典文学',
                'description'    => '名前のない猫の視点から、明治時代の人間社会を風刺的に描いた夏目漱石の処女長編小説。猫の目を通して見た滑稽な人間模様が魅力。',
                'status'         => '読了',
                'rating'         => 4,
                'read_at'        => '2024-03-15',
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => 'こころ',
                'author'         => '夏目漱石',
                'publisher'      => '新潮社',
                'published_year' => 1914,
                'isbn'           => '978-4-10-109002-4',
                'genre'          => '純文学',
                'description'    => '明治時代の知識人の孤独と罪悪感を描いた名作。「先生」と若者との交流、そして衝撃的な告白の手紙。人間の心の深淵を描く。',
                'status'         => '読了',
                'rating'         => 5,
                'read_at'        => '2024-01-20',
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => '人間失格',
                'author'         => '太宰治',
                'publisher'      => '新潮社',
                'published_year' => 1948,
                'isbn'           => '978-4-10-100701-1',
                'genre'          => '純文学',
                'description'    => '太宰治の自伝的小説。人間社会に馴染めない主人公・葉蔵の「恥の多い生涯」を、三冊のノートと手記という形式で描く。',
                'status'         => '読了',
                'rating'         => 5,
                'read_at'        => '2023-11-10',
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => '羅生門',
                'author'         => '芥川龍之介',
                'publisher'      => '新潮社',
                'published_year' => 1915,
                'isbn'           => '978-4-10-100401-0',
                'genre'          => '短編小説',
                'description'    => '平安時代の京都を舞台に、生き延びるために悪を働くことを正当化する人間の本質を鋭く描いた短編小説。',
                'status'         => '読了',
                'rating'         => 4,
                'read_at'        => '2024-02-05',
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => 'ノルウェイの森',
                'author'         => '村上春樹',
                'publisher'      => '講談社',
                'published_year' => 1987,
                'isbn'           => '978-4-06-264500-6',
                'genre'          => '現代小説',
                'description'    => '1960年代後半の日本を舞台に、喪失と成長を描いた村上春樹の代表作。青春と恋愛の物語。',
                'status'         => '読了',
                'rating'         => 5,
                'read_at'        => '2024-04-10',
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => '海辺のカフカ',
                'author'         => '村上春樹',
                'publisher'      => '新潮社',
                'published_year' => 2002,
                'isbn'           => '978-4-10-353413-6',
                'genre'          => '現代小説',
                'description'    => '15歳の少年・田村カフカが家出をして四国の図書館に辿り着く物語。現実と幻想が交錯する壮大な物語。',
                'status'         => '読中',
                'rating'         => null,
                'read_at'        => null,
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => 'ゼロ・トゥ・ワン',
                'author'         => 'ピーター・ティール',
                'publisher'      => 'NHK出版',
                'published_year' => 2014,
                'isbn'           => '978-4-14-081564-8',
                'genre'          => 'スタートアップ',
                'description'    => 'PayPal創業者による起業論。ゼロから全く新しいものを作り出すことの重要性を説く。スタートアップ必読書。',
                'status'         => '読了',
                'rating'         => 4,
                'read_at'        => '2024-05-20',
                'category_id'    => $business,
                'cover_image_url' => null,
            ],
            [
                'title'          => '嫌われる勇気',
                'author'         => '岸見一郎・古賀史健',
                'publisher'      => 'ダイヤモンド社',
                'published_year' => 2013,
                'isbn'           => '978-4-478-02581-9',
                'genre'          => '哲学・自己啓発',
                'description'    => 'アドラー心理学をわかりやすく解説した一冊。青年と哲人の対話形式で、人間関係の悩みを解決する考え方を提示。',
                'status'         => '読了',
                'rating'         => 5,
                'read_at'        => '2024-06-01',
                'category_id'    => $selfhelp,
                'cover_image_url' => null,
            ],
            [
                'title'          => 'Clean Code',
                'author'         => 'Robert C. Martin',
                'publisher'      => 'Prentice Hall',
                'published_year' => 2008,
                'isbn'           => '978-0-13-235088-4',
                'genre'          => 'プログラミング',
                'description'    => 'ソフトウェアエンジニア必読のコーディングガイド。読みやすく保守しやすいコードを書くための原則と実践を解説。',
                'status'         => '読中',
                'rating'         => null,
                'read_at'        => null,
                'category_id'    => $tech,
                'cover_image_url' => null,
            ],
            [
                'title'          => 'リーダブルコード',
                'author'         => 'Dustin Boswell・Trevor Foucher',
                'publisher'      => 'オライリージャパン',
                'published_year' => 2012,
                'isbn'           => '978-4-87311-566-6',
                'genre'          => 'プログラミング',
                'description'    => 'より良いコードを書くための実用的なアドバイスを集めた書籍。命名、コメント、コードの再構成など幅広いトピックをカバー。',
                'status'         => '読了',
                'rating'         => 4,
                'read_at'        => '2023-12-15',
                'category_id'    => $tech,
                'cover_image_url' => null,
            ],
            [
                'title'          => '坂の上の雲',
                'author'         => '司馬遼太郎',
                'publisher'      => '文藝春秋',
                'published_year' => 1969,
                'isbn'           => '978-4-16-732001-5',
                'genre'          => '歴史小説',
                'description'    => '明治時代の日本を舞台に、日露戦争を中心とした近代日本の歩みを描いた司馬遼太郎の大河小説。秋山兄弟と正岡子規の物語。',
                'status'         => '未読',
                'rating'         => null,
                'read_at'        => null,
                'category_id'    => $history,
                'cover_image_url' => null,
            ],
            [
                'title'          => '鬼滅の刃（1巻）',
                'author'         => '吾峠呼世晴',
                'publisher'      => '集英社',
                'published_year' => 2016,
                'isbn'           => '978-4-08-880723-3',
                'genre'          => '少年漫画',
                'description'    => '大正時代を舞台に、鬼に家族を殺された炭治郎が妹を人間に戻すため鬼狩りとして戦う物語。大ヒット漫画の第1巻。',
                'status'         => '読了',
                'rating'         => 5,
                'read_at'        => '2024-07-05',
                'category_id'    => $manga,
                'cover_image_url' => null,
            ],
            [
                'title'          => 'もし高校野球の女子マネージャーがドラッカーの「マネジメント」を読んだら',
                'author'         => '岩崎夏海',
                'publisher'      => 'ダイヤモンド社',
                'published_year' => 2009,
                'isbn'           => '978-4-478-01203-1',
                'genre'          => 'ビジネス小説',
                'description'    => 'ドラッカーの「マネジメント」を高校野球部に応用するというユニークな発想の小説。経営学を物語形式でわかりやすく解説。',
                'status'         => '未読',
                'rating'         => null,
                'read_at'        => null,
                'category_id'    => $business,
                'cover_image_url' => null,
            ],
            [
                'title'          => '銀河鉄道の夜',
                'author'         => '宮沢賢治',
                'publisher'      => '新潮社',
                'published_year' => 1934,
                'isbn'           => '978-4-10-100701-2',
                'genre'          => '童話・幻想文学',
                'description'    => '孤独な少年ジョバンニが夢の中で銀河鉄道の旅をする物語。宮沢賢治の代表作であり、生と死・友情をテーマにした幻想的な作品。',
                'status'         => '読了',
                'rating'         => 5,
                'read_at'        => '2024-08-12',
                'category_id'    => $novel,
                'cover_image_url' => null,
            ],
            [
                'title'          => '思考の整理学',
                'author'         => '外山滋比古',
                'publisher'      => '筑摩書房',
                'published_year' => 1986,
                'isbn'           => '978-4-480-02826-5',
                'genre'          => '思考法',
                'description'    => '長年にわたってベストセラーを続ける思考法の本。自分の頭で考え、アイデアを生み出すための実践的なヒントが満載。',
                'status'         => '未読',
                'rating'         => null,
                'read_at'        => null,
                'category_id'    => $selfhelp,
                'cover_image_url' => null,
            ],
        ];

        foreach ($books as $bookData) {
            Book::create($bookData);
        }
    }
}
